In [8]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/code/enrichment_fxns.R")

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [9]:
mod_def <- "PosBC"
unique <- FALSE

## Prep DE genes

In [10]:
pairwise_res_list <- readRDS("data/DE_genes/yao_2021_ACA_STAR_donor_cell_type_pseudobulk_pairwise_DE_genes_dream.RDS")
pairwise_ctype_genes <- prep_DE_genes(pairwise_res_list, lfc_threshold, pairwise=TRUE, unique=unique)

## Round 1 (pcntVar = 20, mergeParam = 0.85)

In [18]:
network_dir <- "yao_2021_ACA_STAR_20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.85_Modules"
dataset <- "20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.85"

In [12]:
pairwise_enrichments_df <- get_module_enrichments(network_dir, pairwise_ctype_genes, mod_def)

In [13]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

pairwise_top_mods_df <- pairwise_enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [14]:
pairwise_top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  endothelial_cell
2  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
3  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
4  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
5  oligodendrocyte
6  pvalb_GABAergic_cortical_interneuron
7  L6b_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
10 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
11 sncg_GABAergic_cortical_interneuron
12 sst_chodl_GABAergic_cortical_interneuron
13 lamp5_GABAergic_cortical_interneuron
14 sst_GABAergic_cortical_interneuron
15 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  5.866048e-191 3.236299e-186 blue
2  9.766955e-136 2.694214e-131 turquoise
3  2.198092e-115 1.515859e-111 blue
4   1.783305e-68  1.130861e-65 darkgrey
5   6.124792e-66  3.754498e-63 yellow
6   2.787920e-55  1.201637e-52 green
7   1.143973e-47  4.322806e-45 grey60
8   3.647207e-42  1.183626e-39 orange
9   7.976835e-39  2.200410e-36 lightcyan
10  7.634755e-22  1.102643e-19 red
11  1.045791e-19  1.397005e-17 orange1
12  7.426164e-13  6.932343e-11 midnightblue
13  2.275318e-09  1.758114e-07 orchid
14  5.553511e-05  2.733160e-03 bisque3
15  1.325731e-04  6.074797e-03 turquoise
   Network
1  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
2  Bicor-None_signum0.16_minSize15_merge_ME_0.85_19017
3  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
4  Bicor-None_signum0.342_minSize8_merge_ME_0.85_19017
5  Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
6  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
7  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
8  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
9  Bicor-None_signum0.0856_minSize15_merge_ME_0.85_19017
10 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
11 Bicor-None_signum0.207_minSize4_merge_ME_0.85_19017
12 Bicor-None_signum0.177_minSize15_merge_ME_0.85_19017
13 Bicor-None_signum0.0856_minSize6_merge_ME_0.85_19017
14 Bicor-None_signum0.0856_minSize8_merge_ME_0.85_19017
15 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017

In [19]:
write.csv(pairwise_top_mods_df, file=paste0("data/enrichments/yao_2021_ACA_pairwise_DE_genes_dream_unique", unique, "_", dataset, "_", mod_def, "_top_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 2 (pcntVar = 20, mergeParam = 0.9)

In [ ]:
network_dir <- "yao_2021_ACA_STAR_20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.9_Modules"
dataset <- "20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.9"

In [5]:
pairwise_enrichments_df <- get_module_enrichments(network_dir, pairwise_ctype_genes, mod_def)

In [6]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

pairwise_top_mods_df <- pairwise_enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [7]:
pairwise_top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
2  endothelial_cell
3  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
4  oligodendrocyte
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  pvalb_GABAergic_cortical_interneuron
7  L6b_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
10 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
11 sncg_GABAergic_cortical_interneuron
12 sst_chodl_GABAergic_cortical_interneuron
13 lamp5_GABAergic_cortical_interneuron
14 sst_GABAergic_cortical_interneuron
15 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  4.867242e-133 1.984043e-128 blue
2  5.183388e-113 1.039269e-108 black
3   1.372387e-72  2.358545e-69 turquoise
4   6.760142e-68  1.070059e-64 brown
5   3.526575e-67  5.303087e-64 darkmagenta
6   5.709826e-53  3.150881e-50 yellow
7   1.143973e-47  5.135071e-45 skyblue
8   2.335827e-42  8.836479e-40 sienna3
9   3.698239e-39  1.195963e-36 lightgreen
10  1.468323e-22  2.123068e-20 pink
11  1.045791e-19  1.344110e-17 rosybrown2
12  3.088655e-12  2.676982e-10 saddlebrown
13  2.275318e-09  1.683400e-07 lemonchiffon2
14  5.553511e-05  2.599562e-03 paleturquoise1
15  7.276985e-04  2.625739e-02 blue
   Network
1  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
2  Bicor-None_signum0.205_minSize15_merge_ME_0.9_19017
3  Bicor-None_signum0.341_minSize15_merge_ME_0.9_19017
4  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
5  Bicor-None_signum0.341_minSize8_merge_ME_0.9_19017
6  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
7  Bicor-None_signum0.205_minSize12_merge_ME_0.9_19017
8  Bicor-None_signum0.205_minSize12_merge_ME_0.9_19017
9  Bicor-None_signum0.0858_minSize15_merge_ME_0.9_19017
10 Bicor-None_signum0.341_minSize10_merge_ME_0.9_19017
11 Bicor-None_signum0.205_minSize4_merge_ME_0.9_19017
12 Bicor-None_signum0.147_minSize15_merge_ME_0.9_19017
13 Bicor-None_signum0.0858_minSize6_merge_ME_0.9_19017
14 Bicor-None_signum0.0858_minSize8_merge_ME_0.9_19017
15 Bicor-None_signum0.176_minSize12_merge_ME_0.9_19017

In [ ]:
write.csv(pairwise_top_mods_df, file=paste0("data/enrichments/yao_2021_ACA_pairwise_DE_genes_dream_unique", unique, "_", dataset, "_", mod_def, "_top_Qval_modules.csv"), row.names=FALSE, quote=FALSE)